[package]
name = "pykill"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.25"
crossterm = "0.27"
walkdir = "2.4"
humansize = "2.1"        # For formatting file sizes
chrono = "0.4"           # For timestamps
clap = { version = "4.4", features = ["derive"] }
